### ISSUE TITLE
MMSEQS2 should return some hits when setting -c in iterative searches

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#121]
## Expected Behavior
MMSEQS2 should return some hits when setting `-c` in iterative searches

## Current Behavior
MMSEQS2 returns 0 hits
## Steps to Reproduce (for bugs)
mmseqs createdb QUERY.fasta QUERY
mmseqs createdb DB.fasta DB
mmseqs search QUERY DB results tmp  --num-iterations 2 -e 1e-5 -c 0.4

## MMseqs Output (for bugs)
LOG file: [mmseqs_20180926.log](https://gist.github.com/genomewalker/4a53d096569f0a04bbf5986519c5f037)

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): ** 199d9b81f8cd6af9e66f97ef4dc0bd53c8fce12b**
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): **self-compiled**
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:  **cmake version 3.5.1** and **gcc version 5.4.0**
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): **Running in a [VM](https://gist.github.com/genomewalker/bd70eff7fefd8256d52bc1f267983d5a) with 8 cores and 32GB**
* Operating system and version: **Linux machine1b8b2ea2-4f57-414b-9577-c2897459a784 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by milot-mirdita** [comment]
Thanks for the bug report. We found out whats going wrong. 

If its urgent you can replace in `src/alignment/Alignment.cpp` line 42:
```
        alignmentMode = Parameters::ALIGNMENT_MODE_SCORE_ONLY;
```
with
```
        alignmentMode = Parameters::ALIGNMENT_MODE_SCORE_COV_SEQID;
```

Martin will fix the issue in the coming days in a better way.

**Comment by genomewalker** [comment]
Hi Milot
thank you very much we will wait for Martin's fix

Antonio

**Comment by martin-steinegger** [comment]
This bug should be fixed now. Could you please try if it works for you?

**Comment by genomewalker** [comment]
Hi Martin
now seems to work, the `result_db` contains the hits, but in the log MMSEQS2 still report:
```
All sequences processed.

0 alignments calculated.
0 sequence pairs passed the thresholds (-nan of overall calculated).
0 hits per query sequence.
Time for processing: 0h 0m 1s 872ms
```

**Comment by ChiaraVanni** [comment]
Hi Martin,
I'm still having the same issue.

### Expected Behavior
MMSEQS2 should return some hits when setting -c in iterative searches (profile vs sequence db)

### Current Behavior
MMSEQS2 returns 0 hits when setting `--cov-mode 0` and a coverage threshold higher than `-c 0.2`.

Using different coverage modalities (`--cov-mode 1` or `--cov-mode 2`) works fine.

### Steps to Reproduce (for bugs)
mmseqs createdb QUERY.fasta queryDB
mmseqs createdb DB.fasta targetDB
mmseqs search queryDB queryDB query_aln tmp  --num-iterations 3 --threads 8 -e 1e-05 
mmseqs result2profile queryDB queryDB query_aln query_profile
mmseqs search  query_profile targetDB resultsDB tmp --num-iterations 2 -e 1e-5 -c 0.4

### MMseqs Output (for bugs)
LOG file: mmseqs_171018.log
here https://gist.github.com/ChiaraVanni/817d1fef14aaefce1de6c090e1652f3c

### Your Environment
Include as many relevant details about the environment you experienced the bug in.

Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): **6f1beb2116a7bddad13d1eea994dbdfce303fd79**
Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): self-compiled
For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: cmake version 3.10.12 and gcc version 5.4.0
Server specifications (especially CPU support for AVX2/SSE and amount of system memory): Running in a machine with 80 cores and 2Tb
Operating system and version: Linux 4.9.0-8-amd64 x86_64, Debian GNU/Linux 9

**Comment by martin-steinegger** [comment]
@ChiaraVanni does the error still exist?

**Comment by ChiaraVanni** [comment]
@martin-steinegger yes still exist in the version 9.d36de. And I encountered the same issue searching a sequence database vs a profile database using the --slice-search mode.

**Comment by martin-steinegger** [comment]
@ChiaraVanni I have tested the slice-search/iterative-search using the most recent version of mmseqs but I can not reproduce the error. Maybe it was solved in the mean time. Would you mind testing it again please?

**Comment by martin-steinegger** [comment]
Closing this one due to inactivity — it was answered above and we haven't heard back. If it's still relevant, please reopen with your MMseqs2 version, the exact command, and the full output, and we'll be happy to help. Thanks!
