### ISSUE TITLE
Kmer array overflow. currKmerArrayOffset=0, kmerBufferPos=1024, kmerArraySize=1024.

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#274]
## Expected Behavior
mmseqs2 successfully linclust a 49 sequence protein fasta

## Current Behavior
mmseqs2 complain Kmer array overflow

## Steps to Reproduce (for bugs)
```bash
~/seqdb/JGI/script/mmseqs2/bin/mmseqs createdb DB.fasta DB -v 1
mkdir tmp
~/seqdb/JGI/script/mmseqs2/bin/mmseqs linclust DB DB_clu tmp -c 0.9 --cov-mode 1 --threads 1 -v 1
```

## MMseqs Output (for bugs)
```
Kmer array overflow. currKmerArrayOffset=0, kmerBufferPos=1024, kmerArraySize=1024.
Error: kmermatcher died
```

## Context
The input file DB.fasta and all intermediate files are attached.
[linclust_3300021621.zip](https://github.com/soedinglab/MMseqs2/files/4199615/linclust_3300021621.zip)

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
``MMseqs2 Version: 481696b5f426f991211894d8a855bf9d60065c8f``
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
https://mmseqs.com/latest/mmseqs-linux-sse41.tar.gz
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt
* Operating system and version:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
```

**Comment by martin-steinegger** [comment]
Thank you for the report. Could you please rerun it with the latest version?

**Comment by martin-steinegger** [comment]
oh the error still exists in the newest version

**Comment by martin-steinegger** [comment]
This bug only occurs if very small databases with a less then `1024` k-mers are clustered. 
Quick fix is to increase the `--kmer-per-seq 30`

**Comment by kad-ecoli** [comment]
Could you give a command example to show how to increase the amount of k-mers per sequence e.g. to 30?

**Comment by martin-steinegger** [comment]
~/seqdb/JGI/script/mmseqs2/bin/mmseqs linclust DB DB_clu tmp -c 0.9 --cov-mode 1 --threads 1 -v 1 --kmer-per-seq 30

**Comment by martin-steinegger** [comment]
Should be fixed now. Thank you for reporting. 

if you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to themartinsteinegger at gmail com.

**Comment by kad-ecoli** [comment]
I am afraid the issue is not yet solved. I run mmseqs using the same method on the following set of sequence. mmseqs will again complain about "Kmer array overflow. currKmerArrayOffset=10240, kmerBufferPos=1024, kmerArraySize=11264." if  --kmer-per-seq 30 was not set
[DB.fasta.zip](https://github.com/soedinglab/MMseqs2/files/4252299/DB.fasta.zip)

**Comment by martin-steinegger** [comment]
@kad-ecoli oh, there still seem to be cases where an off by one could occur. I pushed a fix. Could you try the latest version? Thank you for your patience. I got your mail address for the stickers! We will sent them out this week.

**Comment by kad-ecoli** [comment]
The new fix works fine. I also received the stickers. Thank you for the little foxes.
