### ISSUE TITLE
easy-search

### ISSUE THREAD

**Issue by onyonderlea** [soedinglab/MMseqs2#428]
MMseqs Version:  6.f5a1c

After updating MMseqs, the easy-search module does not return a regular 12-column tsv as it used to - instead it only return one column with the query name + some numbers (please see the picture). I used a standard command that always worked before:

  mmseqs easy-search -s 7 QUERY.fasta DB.fasta OUTPUT.tsv $TMPDIR

![image](https://user-images.githubusercontent.com/74455924/112879260-365fb400-90c9-11eb-9e91-9224f2645c78.png)

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by milot-mirdita** [comment]
Could you try with the latest release? Your issue was most likely fixed in the meantime.

**Comment by onyonderlea** [comment]
Indeed - I just downloaded the latest stable version with wget and it works fine! Thanks :)
The problem persists in the latest conda version though, so it may be worth updating that one.

**Comment by milot-mirdita** [comment]
I get release 13 when I create a fresh conda env.
What does `conda list` say when you install MMseqs2?
